# Generated by Django 4.0.4 on 2023-05-16 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dos_alamos', '0003_rename_fecha_reserva_info_remove_reserva_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horadisponible',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horadisponible',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='horario',
        ),
        migrations.AddField(
            model_name='horadisponible',
            name='hora',
            field=models.CharField(blank=True, choices=[('08:00:00', '08:00 AM'), ('09:00:00', '09:00 AM'), ('10:00:00', '10:00 AM'), ('11:00:00', '11:00 AM'), ('12:00:00', '12:00 PM'), ('13:00:00', '01:00 PM'), ('14:00:00', '02:00 PM'), ('15:00:00', '03:00 PM'), ('16:00:00', '04:00 PM'), ('17:00:00', '05:00 PM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='horadisponible',
            name='dia',
            field=models.DateField(blank=True, null=True, verbose_name='dia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellidos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='dos_alamos.horadisponible'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
