# Generated by Django 4.2.1 on 2023-05-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dos_alamos', '0004_remove_horadisponible_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horadisponible',
            name='hora',
            field=models.CharField(blank=True, choices=[('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '01:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='confirmada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
